### ISSUE TITLE
Profile: Adding new Skills, Educations, Experience are not working

### ISSUE THREAD

**Issue by komdil** [srp-internships/MRA.Jobs#373]
Try to add Skills, Educations, Experience from profile. 
It is not working 

Tested on 12/25/2023

![Image](https://github.com/srp-internships/MRA.Jobs/assets/50167116/01a40f22-6619-4cdf-8868-877435abf6cc)

**Comment by adheeeem** [comment]
PR on MRA.Infrastructure
